#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent group lynceus >/dev/null; then
            addgroup --system lynceus
        fi
        if ! getent passwd lynceus >/dev/null; then
            adduser --system --ingroup lynceus --no-create-home \
                --home /nonexistent --shell /usr/sbin/nologin \
                --gecos "Lynceus agent" lynceus
        fi

        if [ ! -e /etc/lynceus/agent.conf ]; then
            install -o root -g lynceus -m 0640 \
                /etc/lynceus/lynceus-agent.conf.example /etc/lynceus/agent.conf
        fi

        chown -R lynceus:lynceus /var/log/lynceus

        systemctl daemon-reload >/dev/null 2>&1 || true
        ;;
esac

# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'lynceus-agent.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'lynceus-agent.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'lynceus-agent.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'lynceus-agent.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'lynceus-agent.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0