#!/bin/sh
set -e

case "$1" in
    purge)
        rm -rf /etc/lynceus /var/log/lynceus
        if getent passwd lynceus >/dev/null; then
            deluser --system lynceus >/dev/null 2>&1 || true
        fi
        if getent group lynceus >/dev/null; then
            delgroup --system lynceus >/dev/null 2>&1 || true
        fi
        ;;
esac

# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'lynceus-agent.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0