#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        systemctl stop lynceus-agent >/dev/null 2>&1 || true
        ;;
esac

# Automatically added by dh_installsystemd/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'lynceus-agent.service' >/dev/null || true
fi
# End automatically added section


exit 0